# Streamlit secrets configuration
# This file should be placed in .streamlit/secrets.toml for local development
# For production, use Streamlit Cloud secrets management

[database]
host = "localhost"
port = 5432
user = "postgres"
password = "postgres"
database = "club_analytics"

[email]
smtp_host = "smtp.gmail.com"
smtp_port = 587
smtp_user = "your-email@gmail.com"
smtp_password = "your-app-password"

[monitoring]
sentry_dsn = "https://your-sentry-dsn@sentry.io/project-id"

[slack]
webhook_url = "https://hooks.slack.com/services/YOUR/SLACK/WEBHOOK"
